### ISSUE TITLE
no u

### ISSUE THREAD

**Issue by NaimBoufridi** [NaimBoufridi/WhatsThat#2]
_Originally posted by @ScottyFillups in https://github.com/_render_node/MDU6SXNzdWUzNjI5NjMxNDE=/issues/unread_timeline#issuecomment-423835086_

**Comment by NaimBoufridi** [comment]
No u

**Comment by philipjscott** [comment]
no u

**Comment by philipjscott** [comment]
closing b/c im a boss

**Comment by philipjscott** [comment]
get rekt noob
