### ISSUE TITLE
no u issue 2

### ISSUE THREAD

**Issue by NaimBoufridi** [NaimBoufridi/WhatsThat#3]
_Originally posted by @ScottyFillups in https://github.com/NaimBoufridi/WhatsThat/issues/1#issuecomment-423835086_

**Comment by NaimBoufridi** [comment]
I have issue pls

**Comment by philipjscott** [comment]
ya u have an issue bud

**Comment by philipjscott** [comment]
1v1 me in haxball

**Comment by philipjscott** [comment]
u like my thumbdown emoji? rekt :fire:

**Comment by NaimBoufridi** [comment]
Well played 2 smert 4 me
